# .github/FUNDING.yml

github: [DataWizual]  # Твой GitHub username
# patreon: yourusername   # Если есть Patreon
# open_collective: your-project  # Если есть Open Collective
# ko_fi: yourusername    # Если есть Ko-fi
# tidelift: npm/your-package  # Если в npm
# community_bridge: your-project  # Если в Community Bridge
# liberapay: yourusername  # Если в Liberapay
# issuehunt: yourusername  # Если в IssueHunt
# lfx_crowdfunding: your-project  # Если в LFX Crowdfunding
# polar: yourusername  # Если в Polar
# buy_me_a_coffee: yourusername  # Если в Buy Me a Coffee
# thanks_dev: yourusername  # Если в Thanks.dev